apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: anz-name-space
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
  selector:
    app: communication-service
