apiVersion: v1
kind: Service
metadata:
  name: squirrel-api-service
  namespace: anz-name-space
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: squirrel-api
