apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  namespace: anz-name-space
  labels:
    app: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
        - name: communication-service
          image: squirrel.jfrog.io/squirrel-communication-service/communication-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: LOAD_BALANCER_ADDRESS
              value: 35.244.112.73
            - name: jasypt.encryptor.password
              value: Anil@123
      imagePullSecrets:
        - name: registrypullsecret